# site meta
site_name: 'Record Stack Overflow'
site_description: 'Documentation Site for the Record Stack Overflow API'
site_author: 'Ryan Seymour'

# copyright
copyright: 'Copyright &copy; 2019 Ryan Seymour'

# configuration
theme:
  name: 'material'
  logo:
    icon: 'library_music'
  favicon: 'assets/images/baseline_music_note_black_18dp.png'
  
# navigation
nav:
- Home: index.md
- Getting Started:
  - Authentication: getting-started/authentication.md
  - Create a customer account: getting-started/customer-account.md
  - Create a merchant account: getting-started/merchant-account.md
  - Sending your first request: getting-started/sending-first-request.md
# - REST(ful) API: rest.md
- Response Codes: response-codes.md
- Rate Limiting: rate-limiting.md
# - Code Samples: code-samples.md
- Records: records.md
- Orders: orders.md
- Merchants: merchants.md
- Customers: customers.md
- Quick Reference Library: quick-reference.md
- API Glossary: api-glossary.md
# - API Best Practices: api-best-practices.md

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
